apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ci-cd-demo.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "ci-cd-demo.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ci-cd-demo.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
