apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ci-cd-demo.fullname" . }}-vault-secrets
  labels:
    app: {{ include "ci-cd-demo.name" . }}
type: Opaque
data:
  vault-token: {{ .Values.secrets.vaultToken | b64enc }}
  vault-address: {{ .Values.secrets.vaultAddr | b64enc }}
