apiVersion: v1
kind: Service
metadata:
  name: {{ include "ci-cd-demo.fullname" . }}
  labels:
    app: {{ include "ci-cd-demo.name" . }}
spec:
  selector:
    app: {{ include "ci-cd-demo.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
